<?php

return [
    'BTG' => [
        'api_domain' => env('BTG_API_DOMAIN'),
        'domain' => '',
        'app_id' => env('BTG_APP_ID'),
        'app_secret' => env('BTG_APP_SECRET'),
        'admin_url' => env('BTG_ADMIN_URL'),
        'admin_user' => env('BTG_ADMIN_USER'),
        'admin_password' => env('BTG_ADMIN_PASSWORD'),
    ],
    'WM' => [
        'api_domain' => env('WM_API_DOMAIN'),
        'domain' => '',
        'app_id' => env('WM_APP_ID'),
        'app_secret' => env('WM_APP_SECRET'),
        'admin_url' => env('WM_ADMIN_URL'),
        'admin_user' => env('WM_ADMIN_USER'),
        'admin_password' => env('WM_ADMIN_PASSWORD'),
    ],
    'RSG' => [
        'api_domain' => env('RSG_API_DOMAIN'),
        'domain' => '',
        'app_id' => env('RSG_APP_ID'),
        'app_secret' => env('RSG_APP_SECRET'),
        'SystemCode' => env('RSG_SYSTEMCODE'),
        'WebId' => env('RSG_WEBID'),
        'DesKey' => env('RSG_DESKEY'),
        'DesIV' => env('RSG_DESIV'),
    ],
    'RSG_LIVE' => [
        'api_domain' => env('RSG_LIVE_API_DOMAIN'),
        'client_id' => env('RSG_LIVE_CLIENT_ID'),
        'client_secret' => env('RSG_LIVE_CLIENT_SECRET'),
        'SystemCode' => env('RSG_LIVE_SYSTEMCODE'),
        'WebId' => env('RSG_LIVE_WEBID'),
        'DesKey' => env('RSG_LIVE_DESKEY'),
        'DesIV' => env('RSG_LIVE_DESIV'),
    ],
    'ATG' => [
        'api_domain' => env('ATG_API_DOMAIN'),
        'operator' => env('ATG_OPERATOR'),
        'providerId' => env('ATG_PROVIDERID'),
        'key' => env('ATG_KEY'),
    ],
    'DG' => [
        'api_domain' => env('DG_API_DOMAIN'),
        'domain' => '',
        'app_id' => env('DG_APP_ID'),
        'app_secret' => env('DG_APP_SECRET'),
        'admin_url' => env('DG_ADMIN_URL'),
        'admin_user' => env('DG_ADMIN_USER'),
        'admin_password' => env('DG_ADMIN_PASSWORD'),
        'agent_fix' => env('DG_AGENT_FIX'),
        'agent_suffix' => env('DG_AGENT_SUFFIX'),
    ],
    'JDB' => [
        'api_domain' => env('JDB_API_DOMAIN'),
        'domain' => '',
        'dc' => env('JDB_DC'),
        'IV' => env('JDB_IV'),
        'KEY' => env('JDB_KEY')
    ],
    'KY' => [
        'api_domain' => env('KY_API_DOMAIN'),
        'api_record_domain' => env('KY_API_RECORD_DOMAIN'),
        'domain' => '',
        'agent' => env('KY_AGENT'),
        'des_key' => env('KY_DES_KEY'),
        'md5_key' => env('KY_MD5_KEY'),
        'line_code' => env('KY_LINE_CODE')
    ],
    'KYS' => [
        'api_domain' => env('KYS_API_DOMAIN'),
        'api_record_domain' => env('KYS_API_RECORD_DOMAIN'),
        'domain' => '',
        'agent' => env('KYS_AGENT'),
        'des_key' => env('KYS_DES_KEY'),
        'md5_key' => env('KYS_MD5_KEY'),
        'line_code' => env('KYS_LINE_CODE')
    ],
    'SPS' => [
        'api_domain' => env('SPS_API_DOMAIN'),
        'domain' => '',
        'api_key' => env('SPS_API_KEY'),
        'vendor_id' => env('SPS_VENDORID'),
        'password' => env('SPS_PASSWORD'),
        'signature' => env('SPS_SIGNATURE')
    ],
    'YZG' => [
        'api_domain' => env('YZG_API_DOMAIN'),
        'domain' => '',
        'dc' => env('YZG_DC'),
        'IV' => env('YZG_IV'),
        'KEY' => env('YZG_KEY'),
        'AGENT' => env('YZG_AGENT')
    ],
    'MT' => [
        'api_domain' => env('MT_API_DOMAIN'),
        'system_code' => env('MT_SYSTEM_CODE'),
        'web_id' => env('MT_WEB_ID'),
        'client_id' => env('MT_CLIENT_ID'),
        'client_secret' => env('MT_CLIENT_SECRET'),
        'des_key' => env('MT_DES_KEY'),
        'des_iv' => env('MT_DesIV'),
    ],
    'OB' => [
        'api_domain' => env('OB_API_DOMAIN'),
        'agent' => env('OB_AGENT'),
        'operator_id' => env('OB_OPERATOR_ID'),
        'suffix' => env('OB_SUFFIX'),
        'key' => env('OB_KEY'),
    ],
    'O8' => [
        'api_domain' => env('O8_API_DOMAIN'),
        'client_id' => env('O8_CLIENT_ID'),
        'client_secret' => env('O8_CLIENT_SECRET'),
    ],
    'TNINE' => [
        'api_domain' => env('TNINE_API_DOMAIN'),
        'agent_id' => env('TNINE_AGENT_ID'),
        'api_key' => env('TNINE_API_KEY'),
    ],
    'TNINE_SLOT' => [
        'api_domain' => env('TNINE_SLOT_API_DOMAIN'),
        'agent_id' => env('TNINE_SLOT_AGENT_ID'),
        'api_key' => env('TNINE_SLOT_API_KEY'),
    ],
    'SP' => [
        'api_domain' => env('SP_API_DOMAIN'),
        'des_key' => env('SP_DES_KEY'),
        'md5_key' => env('SP_MD5_KEY'),
        'secret' => env('SP_SECRET'),
        'key' => env('OB_KEY'),
    ],
    'SPSDY' => [
        'api_domain' => env('SPS_DY_API_DOMAIN'),
        'api_key' => env('SPS_DY_API_KEY'),
        'vendor_id' => env('SPS_DY_VENDORID'),
        'password' => env('SPS_DY_PASSWORD'),
        'signature' => env('SPS_DY_SIGNATURE'),
    ],
    'SA' => [
        'api_domain' => env('SA_API_DOMAIN'),
        'des_key' => env('SA_DES_KEY'),
        'md5_key' => env('SA_MD5_KEY'),
        'secret' => env('SA_SECRET'),
    ],
    'KT' => [
        'api_domain' => env('KT_API_DOMAIN'),
        'platform' => env('KT_PLATFORM'),
        'hash_key' => env('KT_HASH_KEY'),
        'agent' => env('KT_AGENT'),
    ],
];
